module.exports = {
  AUDIO_CALL_ADV: 0,
  AUDIO_CALL_COMPLETE: 1,
  VIDEO_CALL_ADV: 2,
  VIDEO_CALL_COMPLETE: 3,
  ON_STREAM_COINS: 4,
  ON_CALL_COINS: 5,
  ON_STREAM_ACTIVITY: 6,
  ON_CALL_ACTIVITY: 7,
  VIEWER_REFUND: 8,
  SYS_ADMIN: 9,
}
